### ISSUE TITLE
Option to enable/disable S3 accelerate uploading

### ISSUE THREAD

**Issue by yyyar** [FallenTech/streaming-s3#14]
Would be very nice to have.
http://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html

`var s3 = new aws.S3({useAccelerateEndpoint: true});`
(from https://stackoverflow.com/questions/37437782/aws-transfer-acceleration-with-pre-signed-urls-using-javascript-sdk)

It may be done globally (since it uses aws.config.update) by passing awsConfig.useAccelerateEndpoint to streaming-s3, but not for one concrete upload.

Otherwise it would be good to have constructor of streaming-s3 to pass parameters to new aws.S3. 

Thanks!

**Comment by talha-asad** [comment]
Thanks, looks like a cool option. I'm planning to release a new version which exposes a way to take any arbitrary options or take an AWS instance.
