### ISSUE TITLE
You committed test.mp4

### ISSUE THREAD

**Issue by jpiepkow** [FallenTech/streaming-s3#15]
You committed test.mp4 to the lib in npm v0.4.3. Please remove it as it adds almost 40mb to a lib that should be under 1mb. Until it is removed I will have to fork to a private repo.

**Comment by talha-asad** [comment]
I never committed that file, npm must have been acting smart. I'll publish a new version. Thanks for the heads up.

**Comment by talha-asad** [comment]
Done, use version 0.4.4

**Comment by jpiepkow** [comment]
Thanks!
