### ISSUE TITLE
aws-sdk versioning issue

### ISSUE THREAD

**Issue by acommodari** [FallenTech/streaming-s3#21]
Hello!

I was wondering if it would be possible to make aws-sdk a peer dependency or to change the dependencies so that they are not locked to an exact version? (maybe allow for any aws-sdk v2 and up?)

I am running into an issue where streaming-s3 is using an outdated aws-sdk which triggers vulnerability warnings.

It also is causing us to have 2 versions of aws-sdk in our node_modules. This is because of the mismatch between our direct aws-sdk dependency and your projects dependency. This is drastically increasing the size of our project and our project is size sensitive.

An update would be great because this is becoming a blocker for our workflow. 

Thank you!

**Comment by acommodari** [comment]
@talha-asad I created a PR to fix some of the open issues 
#22 
please have a look and give some feedback thanks!!

**Comment by talha-asad** [comment]
Thanks for the fixes and updates!
