### ISSUE TITLE
internal server error in server and Error: AWS did not acknowledge all parts within specified timeout of 60 seconds. 

### ISSUE THREAD

**Issue by periyasamy25** [FallenTech/streaming-s3#9]
1.When i run a code in local(my system) to upload 25mb video i got the error that - "Error: AWS did not acknowledge all parts within specified timeout of 60 seconds." 
2.When i run a code in server to upoad same 25mb video i got the error that "internal server error".
3.If i upload 200mb file it shows "Request Entity Too Large".

Please help me to solve this problem.

**Comment by talha-asad** [comment]
Please share your code so that i could reproduce any of these situations.

**Comment by world** [comment]
I have been using this module for many months in production and oddly JUST got that message twice today! Any ideas? Is this npm dead? Should we move on? It's a great module!

**Comment by talha-asad** [comment]
You probably need to play around with `waitTime` setting.
